services:
  # Our PostgreSQL Database
  db:
    # Using the latest PostgreSQL image
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  # Database management interface
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080


  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - "9090:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - keycloak-data:/opt/keycloak/data
    command: 
      - start-dev
      - --db=dev-file


volumes:
  keycloak-data:
    driver: local